title: AOSP Kernel Builder
tagline: ZenMaxBuilder (ZMB) | AOSP Kernel Builder
description: ZenMaxBuilder (ZMB) by darkmaster @grm34
url: https://kernel-builder.com
author:
  name: darkmaster @grm34
  url: https://githhub.com/grm34
google_analytics: G-XRXTP3G5KE
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
theme: jekyll-theme-hacker
