title: Android Kernel Builder
tagline: ZenMaxBuilder (ZMB) | Android Kernel Builder
description: ZenMaxBuilder (ZMB) The perfect Tool to compile on the fly
url: https://kernel-builder.com
author:
  name: darkmaster @grm34 Neternels Team
  url: https://githhub.com/grm34
google_analytics: G-XRXTP3G5KE
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
theme: jekyll-theme-hacker
