name: Automerge ZenMaxBuilder PR

on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked

  workflow_dispatch:

  pull_request_review:
    types:
      - submitted

  check_suite:
    types:
      - completed

  status: {}

jobs:
  automerge:
    if: github.repository == 'grm34/ZenMaxBuilder'
    runs-on: ubuntu-latest
    steps:
      - id: automerge
        name: automerge
        uses: "pascalgn/automerge-action@v0.15.3"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: "automerge"
          BASE_BRANCHES: "zmb"
          MERGE_METHOD: "squash"
          UPDATE_METHOD: "merge"
          MERGE_REQUIRED_APPROVALS: "0"
          MERGE_FORKS: "false"
