name: Updates ZenMaxBuilder Installer

on:
  push:
    branches: [ "zmb" ]
    paths:
      - "./src/install.sh"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: "BOT: updates zmb installer (docs/zmb)"
          title: "BOT: updates zmb installer (docs/zmb)"
          body: "Signed-off-by: grm34 <jerem.pardo@tutanota.com>"
          branch: install

      - name: Copy the installer
        run: |
          cp -f "./src/install.sh" "./docs/zmb"

      - name: Commit changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "Updates ZMB installer" -a
