name: Updates ZenMaxBuilder Installer

on:
  push:
    branches: [ "zmb" ]
    paths:
      - src/install.sh

  workflow_dispatch:

jobs:
  update-installer:
    if: github.repository == 'grm34/ZenMaxBuilder'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: zmb
          fetch-depth: 0

      - name: Creates new branch
        run: |
          git checkout -b "up2date" "zmb"

      - name: Copy ZMB installer
        run: |
          cp -f "./src/install.sh" "./docs/zmb"

      - name: Commit changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "BOT: updates zmb installer (docs/zmb)" -a

      - name: Push changes
        run: |
          git push origin "up2date"

      - name: Create Pull Request
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | gh auth login --with-token
          gh pr create -B "zmb" -H "up2date" -f
          sleep 60
          gh pr edit --add-label "automerge"
