name: ZenMaxBuilder Installer

on:
  push:
    branches: [ "zmb" ]
    paths:
      - "./src/install.sh"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Copy the installer
        run: |
          cp -f "./src/install.sh" "./docs/zmb"

      - name: Commit changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "Updates ZMB installer" -a

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          force_with_lease: true
